#!/bin/sh
set -e
./build

# echo abc123 > test
# chmod 0664 test
# tar --mtime="@0" -H v7 -cf tmp2.tar test

ape ./funcWebWiki-kernel.com -- --trigger genSiteTar > tmp.tar

rm -rf static-dir
mkdir static-dir
cd static-dir
tar -xf ../tmp.tar
