#!/bin/sh
./build
# redbean-3.0.0 doesn't support -*
cp thirdparty/redbean-2.2.com funcWebWiki-rx.com
cd kernel
zip --quiet -r ../funcWebWiki-rx.com .
cd ..
zip --quiet -r ../funcWebWiki-rx.com thirdparty/licenses thirdparty/redbean-3.0.0-licenses.txt
ape ./funcWebWiki-rx.com -* -- --asset-wiki --pack --continue
